spring:
  application:
    name: Backend

  datasource:
    mysql:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/cloudBalance?serverTimezone=UTC
        username: clouduser
        password: Cloud@123
        driver-class-name: com.mysql.cj.jdbc.Driver

    snowflake:
      url: jdbc:snowflake://tagolxl-nu26032.snowflakecomputing.com
      username: MANISHRWT15
      password: Manishrawat@2001
      driver-class-name: net.snowflake.client.jdbc.SnowflakeDriver
      warehouse: CLOUDBALANCE_WH
      database: CLOUDBALANCE_DB
      schema: COST

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.boot: INFO

app:
  jwt-secret: JWT_SECRET:ZGV2X2p3dF9zZWNyZXRfa2V5XzEyM19sb25nX2FuZF9zZWN1cmU=
  jwt-token-expiry: 900000